const CATALOG = [
  { cat: "Moto", sub: "Bougies", name: "Bougie A6", quality: "", priceUnit: 300, priceCarton: 2000, stock: "Disponible", photo: "bougie_a6.jpg" },
  { cat: "Moto", sub: "Bougies", name: "Bougie A7", quality: "Qualité 1", priceUnit: 300, priceCarton: 1250, stock: "Disponible", photo: "bougie_a7_q1.jpg" },
  { cat: "Moto", sub: "Bougies", name: "Bougie A7", quality: "Qualité 2", priceUnit: 300, priceCarton: 1500, stock: "Disponible", photo: "bougie_a7_q2.jpg" },
  { cat: "Moto", sub: "Bougies", name: "Bougie A8", quality: "", priceUnit: 300, priceCarton: 2750, stock: "Disponible", photo: "bougie_a8.jpg" },
  { cat: "Moto", sub: "Soupapes", name: "Soupape 110", quality: "", priceUnit: null, priceCarton: 500, stock: "Disponible", photo: "soupape_110.jpg" },
  { cat: "Moto", sub: "Soupapes", name: "Soupape 125", quality: "", priceUnit: null, priceCarton: 500, stock: "Disponible", photo: "soupape_125.jpg" },
  { cat: "Moto", sub: "Soupapes", name: "Soupape 150", quality: "", priceUnit: null, priceCarton: 500, stock: "Disponible", photo: "soupape_150.jpg" },
  { cat: "Moto", sub: "Châteaux", name: "Château Krypton", quality: "", priceUnit: null, priceCarton: 5000, stock: "Disponible", photo: "chateau_krypton.jpg" },
  { cat: "Moto", sub: "Châteaux", name: "Château Spark", quality: "Qualité 1", priceUnit: null, priceCarton: 5000, stock: "Disponible", photo: "chateau_spark_q1.jpg" },
  { cat: "Moto", sub: "Châteaux", name: "Château Spark", quality: "Qualité 2 (Original)", priceUnit: null, priceCarton: 6000, stock: "Disponible", photo: "chateau_spark_q2.jpg" },
  { cat: "Moto", sub: "Chaînes", name: "Chaîne 428", quality: "", priceUnit: null, priceCarton: 1500, stock: "Disponible", photo: "chaine_428.jpg" },
  { cat: "Moto", sub: "Chaînes", name: "Chaîne 420", quality: "", priceUnit: null, priceCarton: 1500, stock: "Disponible", photo: "chaine_420.jpg" },
  { cat: "Moto", sub: "Fredo", name: "Fredo Sirius", quality: "Qualité 1", priceUnit: null, priceCarton: 750, stock: "Disponible", photo: "fredo_sirius_q1.jpg" },
  { cat: "Moto", sub: "Fredo", name: "Fredo Sirius", quality: "Qualité 2", priceUnit: null, priceCarton: 1250, stock: "Disponible", photo: "fredo_sirius_q2.jpg" },
  { cat: "Moto", sub: "Fredo", name: "Fredo Sirius", quality: "Qualité 3", priceUnit: null, priceCarton: 1500, stock: "Disponible", photo: "fredo_sirius_q3.jpg" },
  { cat: "Moto", sub: "Fredo", name: "Fredo Taxi moto", quality: "", priceUnit: null, priceCarton: 1000, stock: "Disponible", photo: "fredo_taxi_moto.jpg" },
  { cat: "Moto", sub: "Fredo", name: "Fredo Krypton", quality: "", priceUnit: null, priceCarton: 750, stock: "Disponible", photo: "fredo_krypton.jpg" },
  { cat: "Moto", sub: "Transmissions", name: "Transmission Sirius", quality: "Qualité 1", priceUnit: null, priceCarton: 2750, stock: "Disponible", photo: "transmission_sirius_q1.jpg" },
  { cat: "Moto", sub: "Transmissions", name: "Transmission Sirius", quality: "Qualité 2", priceUnit: null, priceCarton: 3000, stock: "Disponible", photo: "transmission_sirius_q2.jpg" },
  { cat: "Moto", sub: "Transmissions", name: "Transmission Sirius", quality: "Qualité 3", priceUnit: null, priceCarton: 4000, stock: "Disponible", photo: "transmission_sirius_q3.jpg" },
  { cat: "Moto", sub: "Transmissions", name: "Transmission Sirius", quality: "Qualité 4", priceUnit: null, priceCarton: 5000, stock: "Disponible", photo: "transmission_sirius_q4.jpg" },
  { cat: "Moto", sub: "Transmissions", name: "Transmission Sirius", quality: "Qualité 5", priceUnit: null, priceCarton: 7500, stock: "Disponible", photo: "transmission_sirius_q5.jpg" },
  { cat: "Moto", sub: "Transmissions", name: "Transmission Vegas", quality: "", priceUnit: null, priceCarton: 3500, stock: "Disponible", photo: "transmission_vegas.jpg" },
  { cat: "Moto", sub: "Transmissions", name: "Transmission 115", quality: "", priceUnit: null, priceCarton: 3500, stock: "Disponible", photo: "transmission_115.jpg" },
  { cat: "Moto", sub: "Disques de frein", name: "Disque de frein 125", quality: "", priceUnit: null, priceCarton: null, stock: "Disponible", photo: "disque_125.jpg" },
  { cat: "Moto", sub: "Disques de frein", name: "Disque de frein Krypton 150", quality: "", priceUnit: null, priceCarton: null, stock: "Disponible", photo: "disque_krypton_150.jpg" },
  { cat: "Vélo", sub: "Paniers", name: "Panier avant vélo", quality: "", priceUnit: null, priceCarton: null, stock: "Disponible", photo: "panier_avant_velo.jpg" },
];
